import { IconAnimals, IconProfessions, IconSports } from "assets/shop-icons";

import type { ThemeItem } from "./types";

export const THEMES: Array<ThemeItem> = [
  {
    title: "Еда",
    value: "food",
    price: 0,
    icon: IconSports,
    icons: [
      "Tumbler Glass",
      "Waffle",
      "Watermelon",
      "Wine Glass",
      "Avocado",
      "Baby Bottle",
      "Bacon",
      "Bagel",
      "Baguette Bread",
      "Banana",
      "Beer Mug",
      "Bell Pepper",
      "Bento Box",
      "Beverage Box",
      "Birthday Cake",
      "Blueberries",
      "Bone",
      "Bottle With Popping Cork",
      "Bowl With Spoon",
      "Bread",
      "Broccoli",
      "Bubble Tea",
      "Burrito",
      "Butter",
      "Candy",
      "Canned Food",
      "Carrot",
      "Cheese Wedge",
      "Cherries",
      "Chestnut",
      "Chocolate Bar",
      "Chopsticks",
      "Clinking Beer Mugs",
      "Clinking Glasses",
      "Cocktail Glass",
      "Coconut",
      "Cooked Rice",
      "Cookie",
      "Cooking",
      "Croissant",
      "Cucumber",
      "Cup With Straw",
      "Cupcake",
      "Curry Rice",
      "Custard",
      "Cut Of Meat",
      "Dango",
      "Doughnut",
      "Dumpling",
      "Ear Of Corn",
      "Egg",
      "Eggplant",
      "Falafel",
      "Flatbread",
      "Fondue",
      "Fork And Knife With Plate",
      "Fork And Knife",
      "Fortune Cookie",
      "French Fries",
      "Fried Shrimp",
      "Garlic",
      "Glass Of Milk",
      "Grapes",
      "Green Apple",
      "Green Salad",
      "Hamburger",
      "Honey Pot",
      "Hot Beverage",
      "Hot Dog",
      "Hot Pepper",
      "Ice Cream",
      "Ice",
      "Kitchen Knife",
      "Kiwi Fruit",
      "Leafy Green",
      "Lemon",
      "Lollipop",
      "Mango",
      "Mate",
      "Meat On Bone",
      "Melon",
      "Moon Cake",
      "Mushroom",
      "Oden",
      "Olive",
      "Onion",
      "Oyster",
      "Pancakes",
      "Peach",
      "Peanuts",
      "Pear",
      "Pie",
      "Pineapple",
      "Pizza",
      "Popcorn",
      "Pot Of Food",
      "Potato",
      "Poultry Leg",
      "Pretzel",
      "Red Apple",
      "Rice Ball",
      "Rice Cracker",
      "Roasted Sweet Potato",
      "Sake",
      "Salt",
      "Sandwich",
      "Shallow Pan Of Food",
      "Shaved Ice",
      "Shortcake",
      "Soft Ice Cream",
      "Spaghetti",
      "Spoon",
      "Steaming Bowl",
      "Strawberry",
      "Stuffed Flatbread",
      "Sushi",
      "Taco",
      "Takeout Box",
      "Tamale",
      "Tangerine",
      "Teacup Without Handle",
      "Tomato",
      "Tropical Drink"
    ]
  },
  {
    title: "Путешествия",
    value: "travel",
    price: 200,
    icon: IconProfessions,
    icons: [
      "Airplane Departure",
      "Airplane",
      "Ambulance",
      "Anchor",
      "Articulated Lorry",
      "Auto Rickshaw",
      "Automobile",
      "Baggage Claim",
      "Bank",
      "Beach With Umbrella",
      "Bicycle",
      "Bridge At Night",
      "Building Construction",
      "Bullet Train",
      "Bus Stop",
      "Bus",
      "Camping",
      "Carousel Horse",
      "Castle",
      "Church",
      "Cityscape At Dusk",
      "Cityscape",
      "Classical Building",
      "Construction",
      "Convenience Store",
      "Customs",
      "Delivery Truck",
      "Department Store",
      "Derelict House",
      "Desert Island",
      "Desert",
      "Dollar Banknote",
      "Euro Banknote",
      "Factory",
      "Ferry",
      "Fire Engine",
      "Fireworks",
      "Flying Saucer",
      "Foggy",
      "Helicopter",
      "High Speed Train",
      "Hindu Temple",
      "Horizontal Traffic Light",
      "Hospital",
      "Hotel",
      "House With Garden",
      "House",
      "Houses",
      "Hut",
      "Japanese Castle",
      "Japanese Post Office",
      "Kaaba",
      "Left Luggage",
      "Light Rail",
      "Locomotive",
      "Love Hotel",
      "Map Of Japan",
      "Metro",
      "Milky Way",
      "Minibus",
      "Moai",
      "Monorail",
      "Moon Viewing Ceremony",
      "Mosque",
      "Motor Boat",
      "Motor Scooter",
      "Motorcycle",
      "Motorway",
      "Mount Fuji",
      "Mountain Cableway",
      "Mountain Railway",
      "Mountain",
      "National Park",
      "Night With Stars",
      "Office Building",
      "Oncoming Automobile",
      "Oncoming Bus",
      "Oncoming Police Car",
      "Oncoming Taxi",
      "Parachute",
      "Passenger Ship",
      "Passport Control",
      "Pickup Truck",
      "Police Car Light",
      "Police Car",
      "Post Office",
      "Pound Banknote",
      "Racing Car",
      "Railway Car",
      "Railway Track",
      "Ringed Planet",
      "Rocket",
      "Roller Coaster",
      "Sailboat",
      "Satellite",
      "School",
      "Seat",
      "Shinto Shrine",
      "Ship",
      "Small Airplane",
      "Snow Capped Mountain",
      "Sparkler",
      "Speedboat",
      "Sport Utility Vehicle",
      "Stadium",
      "Station",
      "Sunrise Over Mountains",
      "Sunrise",
      "Sunset",
      "Suspension Railway",
      "Synagogue",
      "Taxi",
      "Tent",
      "Tokyo Tower",
      "Tractor",
      "Train",
      "Tram Car",
      "Tram",
      "Trolleybus",
      "Vertical Traffic Light",
      "Volcano",
      "Wedding",
      "Yen Banknote",
      "Aerial Tramway",
      "Airplane Arrival"
    ]
  },
  {
    title: "Животные",
    value: "animals",
    price: 500,
    icon: IconAnimals,
    icons: [
      "Beaver",
      "Beetle",
      "Bird",
      "Bison",
      "Black Cat",
      "Blossom",
      "Blowfish",
      "Boar",
      "Bouquet",
      "Bug",
      "Butterfly",
      "Cactus",
      "Camel",
      "Carp Streamer",
      "Cat",
      "Cherry Blossom",
      "Chicken",
      "Chipmunk",
      "Christmas Tree",
      "Cloud With Lightning And Rain",
      "Cloud With Lightning",
      "Cloud With Rain",
      "Cloud With Snow",
      "Cloud",
      "Cockroach",
      "Collision",
      "Comet",
      "Cow Face",
      "Cow",
      "Crab",
      "Crescent Moon",
      "Cricket",
      "Crocodile",
      "Dashing Away",
      "Deciduous Tree",
      "Deer",
      "Dizzy",
      "Dodo",
      "Dog Face",
      "Dog",
      "Dolphin",
      "Dove",
      "Dragon Face",
      "Dragon",
      "Duck",
      "Eagle",
      "Elephant",
      "Evergreen Tree",
      "Ewe",
      "Fallen Leaf",
      "Feather",
      "Fire",
      "First Quarter Moon Face",
      "First Quarter Moon",
      "Fish",
      "Flamingo",
      "Fly",
      "Fog",
      "Four Leaf Clover",
      "Fox",
      "Frog",
      "Front Facing Baby Chick",
      "Full Moon Face",
      "Full Moon",
      "Giraffe",
      "Globe Showing Americas",
      "Globe Showing Asia Australia",
      "Globe Showing Europe Africa",
      "Globe With Meridians",
      "Glowing Star",
      "Goat",
      "Gorilla",
      "Guide Dog",
      "Hamster",
      "Hatching Chick",
      "Hear No Evil Monkey",
      "Hedgehog",
      "Herb",
      "Hibiscus",
      "High Voltage",
      "Hippopotamus",
      "Honeybee",
      "Horse Face",
      "Horse",
      "Kangaroo",
      "Koala",
      "Lady Beetle",
      "Last Quarter Moon Face",
      "Last Quarter Moon",
      "Leaf Fluttering In Wind",
      "Leopard",
      "Lion",
      "Lizard",
      "Llama",
      "Lobster",
      "Mammoth",
      "Maple Leaf",
      "Microbe",
      "Monkey Face",
      "Monkey",
      "Mosquito",
      "Mouse Face",
      "Mouse",
      "New Moon Face",
      "New Moon",
      "Octopus",
      "Orangutan",
      "Otter",
      "Owl",
      "Ox",
      "Palm Tree",
      "Panda",
      "Parrot",
      "Paw Prints",
      "Peacock",
      "Penguin",
      "Pig Face",
      "Pig Nose",
      "Pig",
      "Pine Decoration",
      "Polar Bear",
      "Poodle",
      "Potted Plant",
      "Rabbit Face",
      "Rabbit",
      "Raccoon",
      "Ram",
      "Rat",
      "Rhinoceros",
      "Rock",
      "Rooster",
      "Rose",
      "Rosette",
      "Sauropod",
      "Scorpion",
      "Seal",
      "See No Evil Monkey",
      "Seedling",
      "Service Dog",
      "Shamrock",
      "Shark",
      "Sheaf Of Rice",
      "Shooting Star",
      "Shrimp",
      "Skunk",
      "Sloth",
      "Snail",
      "Snake",
      "Speak No Evil Monkey",
      "Spider Web",
      "Spider",
      "Spiral Shell",
      "Spouting Whale",
      "Squid",
      "Star",
      "Sun Behind Cloud",
      "Sun Behind Large Cloud",
      "Sun Behind Rain Cloud",
      "Sun Behind Small Cloud",
      "Sun With Face",
      "Sun",
      "Sunflower",
      "Swan",
      "T Rex",
      "Tanabata Tree",
      "Tiger Face",
      "Tiger",
      "Tropical Fish",
      "Tulip",
      "Turkey",
      "Turtle",
      "Two Hump Camel",
      "Umbrella With Rain Drops",
      "Umbrella",
      "Unicorn",
      "Waning Crescent Moon",
      "Waning Gibbous Moon",
      "Water Buffalo",
      "Water Wave",
      "Waxing Crescent Moon",
      "Waxing Gibbous Moon",
      "Whale",
      "Wilted Flower",
      "Wind Face",
      "Wolf",
      "Worm",
      "Zebra",
      "Ant",
      "Baby Chick",
      "Badger",
      "Bat",
      "Bear"
    ]
  }
];
